ensure valid computer setup; rename logging functions
Logging function warn became fail, and now there's a warn.
Also created a warn quit.

Closes #88.

diff --git a/builds/mac b/builds/mac
--- a/builds/mac
+++ b/builds/mac
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-COMPILED_AT='Mon Oct 19 11:47:51 PDT 2015'
+COMPILED_AT='Mon Oct 19 15:27:29 PDT 2015'
 #
 #  _           _        _ _  __           _
 # (_)_ __  ___| |_ __ _| | |/ _| ___  ___| |_
@@ -155,13 +155,30 @@ function inform () {
 
 function warn () {
   if [[ $2 ]]; then echo ""; fi
+  echo -e "${BG_YELLOW}${BLACK}${BOLD}>>>>  $1 ${RESET}"
+}
+
+function fail () {
+  if [[ $2 ]]; then echo ""; fi
   echo -e "${BG_RED}${WHITE}${BOLD}>>>>  $1 ${RESET}"
 }
 
 function pause_awhile () {
   if [[ $2 ]]; then echo ""; fi
-  echo -e "${BG_YELLOW}${WHITE}${BOLD}>>>>  $1 ${RESET}"
-  read -p "${BG_YELLOW}${WHITE}${BOLD}Press <Enter> to continue.${RESET}"
+  echo -e "${BG_YELLOW}${BLACK}${BOLD}>>>>  $1 ${RESET}"
+  read -p "${BG_YELLOW}${BLACK}${BOLD}Press <Enter> to continue.${RESET}"
+}
+
+function pause_and_warn () {
+  if [[ $2 ]]; then echo ""; fi
+  echo -e "${BG_YELLOW}${BLACK}${BOLD}>>>>  $1 ${RESET}"
+  echo -e "${BG_YELLOW}${BLACK}${BOLD}>>>> ${RESET}"
+  read -p "${BG_YELLOW}${BLACK}${BOLD}>>>>  Continue? [Yy] ${RESET} " -n 1 -r
+
+  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+    fail "Exiting..." true
+    exit 1;
+  fi
 }
 
 #-------------------------------------------------------------------------------
@@ -192,6 +209,86 @@ sudo -p "Password:" echo "${BG_WHITE}> Thank you! ${RESET}"
 OS_VERSION=$(sw_vers -productVersion)
 
 #-------------------------------------------------------------------------------
+# Ensure that the user's computer set up works (mac/os_ensure_valid_setup.sh)
+#-------------------------------------------------------------------------------
+
+COMP_NAME=$(scutil --get ComputerName)
+LOCL_NAME=$(scutil --get LocalHostName)
+HOST_NAME=$(hostname)
+USER_NAME=$(id -un)
+FULL_NAME=$(finger "$USER_NAME" | awk '/Name:/ {print $4" "$5}')
+USER_GRPS=$(id -Gn $USER_NAME)
+OS_NUMBER=$(echo $OS_VERSION | cut -d "." -f 2)
+MAC_ADDRS=$(ifconfig en0 | grep ether | sed -e 's/^[ \t|ether|\s|\n]*//')
+
+DESCRIPTION=`cat << EOFS
+      Computer Type:  Mac OSX $OS_VERSION
+      Long user name: $FULL_NAME
+      Short username: $USER_NAME
+      Computer name:  $COMP_NAME
+      LocalHost name: $LOCL_NAME
+      Full Hostname:  $HOST_NAME
+EOFS`
+
+inform "Loading your computer's information." true
+inform "Your current setup is:"
+printf "$DESCRIPTION\n"
+inform "Checking the validity of this set up."
+inform "If it is not valid, it will fail or warn you."
+echo "..."
+
+# Check if current user is admin.
+
+if echo "$USER_GRPS" | grep -q -w admin; then
+  echo "" > /dev/null
+else
+  fail "The current user does not have administrator privileges. You must " true
+  fail "  run this program from an admin user. Ask an instructor for help."
+  fail "Exiting..." true
+  exit 1
+fi
+
+# Check if OS version is valid.
+
+if [ "$OS_NUMBER" -lt "6" ]; then
+  fail "You need to have Mac OS X 10.6 (Snow Leopard) or higher installed" true
+  fail "  in order to take WDI. Please contact an instructor or producer."
+  fail "Exiting..." true
+  exit 1
+fi
+
+if [ "$OS_NUMBER" -eq "6" ]; then
+  warn "Warning!" true
+  warn "While you can take WDI with  Mac OS X 10.6 (Snow Leopard), it is "
+  warn "  not supported by this script. You can continue to run the      "
+  warn "  script, but any problems need to be taken care of by your      "
+  warn "  instructional team. It is recommended that you upgrade your    "
+  pause_and_warn "  computer.                                                      "
+fi
+
+# Check if username is valid.
+
+if [[ "$USER_NAME" =~ " " ]]; then
+  fail "Your username '${USER_NAME}' has a space. This complictes using " true
+  fail "  command line tools, and can even break some programs. Change  "
+  fail "  your username before continuing.                              "
+  fail "Exiting..." true
+  exit 1
+fi
+
+LOWERCASE=$(echo "$USER_NAME" | tr '[A-Z]' '[a-z]')
+if [ "$USER_NAME" != "$LOWERCASE" ]; then
+  warn "Warning!" true
+  warn "Your username '${USER_NAME}' has 'mixed-case'; it should be entirely in "
+  warn "  lowercase. This could lead to some issues where certain tools "
+  warn "  that are case-sensitive, and others that are not, don't work  "
+  warn "  well together. It is suggested that you change your username. "
+  pause_and_warn "  PS: this also goes for your GitHub username!                  "
+fi
+
+show "Setup is valid!"
+
+#-------------------------------------------------------------------------------
 # Update software on Mac (mac/os_update_software.sh)
 #-------------------------------------------------------------------------------
 
@@ -214,32 +311,32 @@ case $OS_VERSION in
   *10.8*)  cmdline_version="DeveloperToolsCLI"   ;; # Mountain Lion
   *10.7*)  cmdline_version="DeveloperToolsCLI"   ;; # Lion
   *10.6*)  cmdline_version="DeveloperToolsCLILeo"
-           warn "Outdated OS. Considering upgrading before continuing." true;; # Snow Leopard
+           fail "Outdated OS. Considering upgrading before continuing." true;; # Snow Leopard
            # Force the user to upgrade if they're below 10.6
-  *) warn "Sorry! You'll have to upgrade your OS to $MINIMUM_MAC_OS or above." true; exit 1;;
+  *) fail "Sorry! You'll have to upgrade your OS to $MINIMUM_MAC_OS or above." true; exit 1;;
 esac
 
 # Check for Command Line Tools based on OS versions
 if [ ! -z $(pkgutil --pkgs=com.apple.pkg.$cmdline_version) ]; then
   show "Command Line Tools are installed!"
 elif [[ $OS_VERSION == *10.6** ]]; then
-  warn "Command Line Tools are not installed!" true
-  warn "  Downloading and installing the GCC compiler."
-  warn "  When you're done rerun the Installfest script..."
+  fail "Command Line Tools are not installed!" true
+  fail "  Downloading and installing the GCC compiler."
+  fail "  When you're done rerun the Installfest script..."
   curl -OLk https://github.com/downloads/kennethreitz/osx-gcc-installer/GCC-10.6.pkg
   open GCC-10.6.pkg
   exit 1
 elif [[ $OS_VERSION == *10.7* ]] || [[ $OS_VERSION == *10.8* ]]; then
-  warn "Command Line Tools are not installed!" true
-  warn "Register for a Developer Account"
-  warn "  Download the Command Lion Tools from:"
-  warn "    https://developer.apple.com/downloads/index.action"
-  warn "  and then rerun the Installfest script..."
+  fail "Command Line Tools are not installed!" true
+  fail "Register for a Developer Account"
+  fail "  Download the Command Lion Tools from:"
+  fail "    https://developer.apple.com/downloads/index.action"
+  fail "  and then rerun the Installfest script..."
   exit 1
 else
-  warn "Command Line Tools are not installed!" true
-  warn "  Running 'xcode-select --install' Please click continue!"
-  warn "  After installing please rerun the Installfest script..."
+  fail "Command Line Tools are not installed!" true
+  fail "  Running 'xcode-select --install' Please click continue!"
+  fail "  After installing please rerun the Installfest script..."
   xcode-select --install
   exit 1
 fi
@@ -493,7 +590,7 @@ curl -o "$GIT_COMPLETION_FILE" "$GIT_COMPLETION_URL"
 if [[ -e "$GIT_COMPLETION_FILE" ]]; then
   show "File '$GIT_COMPLETION_FILE' created!"
 else
-  warn "${GIT_COMPLETION_FILE} not created... " true
+  fail "${GIT_COMPLETION_FILE} not created... " true
   pause_awhile "Ask an instructor for help if necessary. "
 fi
 
@@ -1098,5 +1195,5 @@ show "Complete!"
 inform "We're done!" true
 echo "#-- fin -- #"
 
-warn "Please quit and re-open your terminal!" true
+fail "Please close your terminal and open a new one!" true
 
diff --git a/builds/mac-test b/builds/mac-test
--- a/builds/mac-test
+++ b/builds/mac-test
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-COMPILED_AT='Mon Oct 19 11:47:51 PDT 2015'
+COMPILED_AT='Mon Oct 19 15:27:29 PDT 2015'
 #
 #  _           _        _ _  __           _
 # (_)_ __  ___| |_ __ _| | |/ _| ___  ___| |_
@@ -155,257 +155,116 @@ function inform () {
 
 function warn () {
   if [[ $2 ]]; then echo ""; fi
+  echo -e "${BG_YELLOW}${BLACK}${BOLD}>>>>  $1 ${RESET}"
+}
+
+function fail () {
+  if [[ $2 ]]; then echo ""; fi
   echo -e "${BG_RED}${WHITE}${BOLD}>>>>  $1 ${RESET}"
 }
 
 function pause_awhile () {
   if [[ $2 ]]; then echo ""; fi
-  echo -e "${BG_YELLOW}${WHITE}${BOLD}>>>>  $1 ${RESET}"
-  read -p "${BG_YELLOW}${WHITE}${BOLD}Press <Enter> to continue.${RESET}"
+  echo -e "${BG_YELLOW}${BLACK}${BOLD}>>>>  $1 ${RESET}"
+  read -p "${BG_YELLOW}${BLACK}${BOLD}Press <Enter> to continue.${RESET}"
 }
+
+function pause_and_warn () {
+  if [[ $2 ]]; then echo ""; fi
+  echo -e "${BG_YELLOW}${BLACK}${BOLD}>>>>  $1 ${RESET}"
+  echo -e "${BG_YELLOW}${BLACK}${BOLD}>>>> ${RESET}"
+  read -p "${BG_YELLOW}${BLACK}${BOLD}>>>>  Continue? [Yy] ${RESET} " -n 1 -r
+
+  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+    fail "Exiting..." true
+    exit 1;
+  fi
+}
+
+# mac/os_version.sh
+
+# Determine OS version
+OS_VERSION=$(sw_vers -productVersion)
 
 #-------------------------------------------------------------------------------
 # Ensure that the user's computer set up works (mac/os_ensure_valid_setup.sh)
 #-------------------------------------------------------------------------------
 
-OS_VERSION="10.7.5"
-
 COMP_NAME=$(scutil --get ComputerName)
 LOCL_NAME=$(scutil --get LocalHostName)
 HOST_NAME=$(hostname)
-USER_NAME=$(whoami)
+USER_NAME=$(id -un)
+FULL_NAME=$(finger "$USER_NAME" | awk '/Name:/ {print $4" "$5}')
 USER_GRPS=$(id -Gn $USER_NAME)
 OS_NUMBER=$(echo $OS_VERSION | cut -d "." -f 2)
+MAC_ADDRS=$(ifconfig en0 | grep ether | sed -e 's/^[ \t|ether|\s|\n]*//')
 
-# OS_VERSION="10.8.5"
-#
-# echo "$OS_VERSION"
-# echo "$USER_NAME"
-# echo "$USER_GRPS"
+DESCRIPTION=`cat << EOFS
+      Computer Type:  Mac OSX $OS_VERSION
+      Long user name: $FULL_NAME
+      Short username: $USER_NAME
+      Computer name:  $COMP_NAME
+      LocalHost name: $LOCL_NAME
+      Full Hostname:  $HOST_NAME
+EOFS`
+
+inform "Loading your computer's information." true
+inform "Your current setup is:"
+printf "$DESCRIPTION\n"
+inform "Checking the validity of this set up."
+inform "If it is not valid, it will fail or warn you."
+echo "..."
+
+# Check if current user is admin.
+
+if echo "$USER_GRPS" | grep -q -w admin; then
+  echo "" > /dev/null
+else
+  fail "The current user does not have administrator privileges. You must " true
+  fail "  run this program from an admin user. Ask an instructor for help."
+  fail "Exiting..." true
+  exit 1
+fi
+
+# Check if OS version is valid.
 
 if [ "$OS_NUMBER" -lt "6" ]; then
-  echo "fail"
+  fail "You need to have Mac OS X 10.6 (Snow Leopard) or higher installed" true
+  fail "  in order to take WDI. Please contact an instructor or producer."
+  fail "Exiting..." true
+  exit 1
 fi
 
 if [ "$OS_NUMBER" -eq "6" ]; then
-  echo "warn"
+  warn "Warning!" true
+  warn "While you can take WDI with  Mac OS X 10.6 (Snow Leopard), it is "
+  warn "  not supported by this script. You can continue to run the      "
+  warn "  script, but any problems need to be taken care of by your      "
+  warn "  instructional team. It is recommended that you upgrade your    "
+  pause_and_warn "  computer.                                                      "
 fi
 
-# check username is valid
-C# warn if is mixed case, can stop and re set
-# fail if spaces, force stop and re set
+# Check if username is valid.
 
-# check computer names etc and print
-
-# check if is admin
-# fail if not, either make admin or etc. (ask instructor)
-
-# ------------------------------------------------------------------------------
-# Clone the script repo locally in order to copy dotfiles etc. directly from it.
-# (settings/script_repo_clone.sh)
-# ------------------------------------------------------------------------------
-
-inform "Downloading the Installfest repo, in order to copy files..." true
-# download the repo for the absolute paths
-
-if [[ $OS_VERSION == *10.6** ]]; then
-  # 10.6 doesn't have git so download the zip and rename it installfest
-  curl -LO https://github.com/ga-instructors/installfest_script/archive/$SCRIPT_REPO_BRANCH.zip
-  unzip $SCRIPT_REPO_BRANCH.zip -d "$SCRIPT_ROOT"
-  mv "$SCRIPT_ROOT/installfest-$SCRIPT_REPO_BRANCH/" "$SCRIPT_DIR"
-else
-  if [[ ! -d $SCRIPT_DIR ]]; then
-    # autoupdate bootstrap file
-    git clone -b $SCRIPT_REPO_BRANCH $SCRIPT_REPO $SCRIPT_DIR
-  else
-    # update repo
-    echo 'Repo already downloaded; updating...'
-    cd $SCRIPT_DIR
-    git pull origin $SCRIPT_REPO_BRANCH
-  fi
+if [[ "$USER_NAME" =~ " " ]]; then
+  fail "Your username '${USER_NAME}' has a space. This complictes using " true
+  fail "  command line tools, and can even break some programs. Change  "
+  fail "  your username before continuing.                              "
+  fail "Exiting..." true
+  exit 1
 fi
 
-show "Repo downloaded!"
+LOWERCASE=$(echo "$USER_NAME" | tr '[A-Z]' '[a-z]')
+if [ "$USER_NAME" != "$LOWERCASE" ]; then
+  warn "Warning!" true
+  warn "Your username '${USER_NAME}' has 'mixed-case'; it should be entirely in "
+  warn "  lowercase. This could lead to some issues where certain tools "
+  warn "  that are case-sensitive, and others that are not, don't work  "
+  warn "  well together. It is suggested that you change your username. "
+  pause_and_warn "  PS: this also goes for your GitHub username!                  "
+fi
 
-#-------------------------------------------------------------------------------
-# Define a utility function to copy over files (settings/util_copy_files.sh)
-#-------------------------------------------------------------------------------
-
-function copy_files () {
-  # params
-  local TYPE_DIR="$1"
-  local TARGET_DIR="$2"
-  local FILE_LIST="$3"
-
-  # placeholder vars
-  local CURRENT_FILE=""
-  local TARGET_FILE=""
-  local BACKUP_FILE=""
-  local DOTFILES=""
-  local BACKED_UP=""
-  local PRINT_LN=""
-
-  local TIMESTAMP=$(date +%s)
-  local PAD="                                       "
-  local BACKUP_DIR="${SCRIPT_ROOT}/${TYPE_DIR}_backups_${TIMESTAMP}"
-
-  # check if the type of files is dotfiles
-  if [[ "$TYPE_DIR" == "dotfiles" ]]; then
-    DOTFILES=true
-  fi
-
-  for FILE_PATH in $FILE_LIST; do
-    CURRENT_FILE=$(basename "$FILE_PATH")
-    if [[ "$DOTFILES" == true ]]; then
-      CURRENT_FILE=".$CURRENT_FILE" # add a dot to dotfiles
-    fi
-
-    # skip NOT-USING files
-    if [[ ! $CURRENT_FILE == *"NOT-USING"* ]]; then
-
-      # print a formatted line describing
-      PRINT_LN="Copying file $CURRENT_FILE... "
-      printf "%s %s" "$PRINT_LN" "${PAD:${#PRINT_LN}}"
-
-      TARGET_FILE="${TARGET_DIR}/${CURRENT_FILE}"
-      BACKUP_FILE="${BACKUP_DIR}/${CURRENT_FILE}"
-
-      # back up files already in the target dir
-      if [[ -e "$TARGET_FILE" ]]; then
-        printf "(File exists! Backing up...)"
-        BACKED_UP=true # save for a final message below
-
-        # ensure the backup dir exists
-        mkdir -p "$BACKUP_DIR"
-        cp "$TARGET_FILE" "$BACKUP_FILE"
-      fi
-
-      # copy the file!
-      cp "$FILE_PATH" "$TARGET_FILE"
-
-      echo "" # flush printed line
-    fi
-  done
-
-  if [[ "$BACKED_UP" == true ]]; then
-    echo "${BOLD}Note: you can find backed-up files in ${BACKUP_DIR}${RESET}"
-  fi
-}
-
-# Usage:
-# copy_files dotfiles "$HOME" "$(echo $SCRIPT_DOTFILES)"
-# copy_files themes "$HOME/Desktop" "TommorrowNight.theme"
-
-#-------------------------------------------------------------------------------
-# Copy over Sublime settiings & packages (settings/sublime_settings_settings.sh)
-#-------------------------------------------------------------------------------
-
-SUBLIME_DIR="${HOME}/Library/Application Support/Sublime Text 3"
-SUBLIME_SETTINGS_DIR="${SUBLIME_DIR}/Packages/User"
-
-# ensure files exist before copying
-mkdir -p "$SUBLIME_SETTINGS_DIR"
-
-inform "Copying Sublime settings..." true
-copy_files subl_settings "$SUBLIME_SETTINGS_DIR" "$SCRIPT_SUBL_SETTINGS"
-show "Complete!"
-
-#-------------------------------------------------------------------------------
-# Copy and install Subl packages (settings/copy_install_sublime_packages.sh)
-#-------------------------------------------------------------------------------
-
-SUBLIME_DIR="${HOME}/Library/Application Support/Sublime Text 3"
-SUBLIME_PACKAGES_DIR="${SUBLIME_DIR}/Installed Packages"
-SUBLIME_SETTINGS_DIR="${SUBLIME_DIR}/Packages/User"
-
-# ensure files exist before copying
-mkdir -p "$SUBLIME_PACKAGES_DIR"
-mkdir -p "$SUBLIME_SETTINGS_DIR"
-
-inform "Copying Sublime packages..." true
-copy_files subl_packages "$SUBLIME_SETTINGS_DIR" "$SCRIPT_SUBL_PACKAGES"
-show "Complete!"
-
-# TODO (pj) get Package Control up and running with settings, etc.
-
-# Install Package Control
-
-PKG_CNTRL_URI="https://packagecontrol.io/Package%20Control.sublime-package"
-PKG_CNTRL_FILE="Package Control.sublime-package"
-
-# # NOTE (phlco) curling then mving because curl gave a malformed url in 10.6
-# mkdir -p "$SRC_DIR/../packages"
-# curl -O "$SRC_DIR/../packages" $PKG_CNTRL_URI
-# mv "$SRC_DIR/../packages" "$SUBLIME_PACKAGES_DIR/$PKG_CNTRL_FILE"
-
-inform "Downloading Sublime Package Control..." true
-curl -o "${SUBLIME_PACKAGES_DIR}/$PKG_CNTRL_FILE" $PKG_CNTRL_URI
-show "Complete!"
-
-#-------------------------------------------------------------------------------
-# Install the cross-platform fonts (mac/os_install_fonts.sh)
-#-------------------------------------------------------------------------------
-
-# Mac OS X used to use Monaco by default in ST, but now uses Menlo.
-# While Menlo works fine, it is OS X only, and is not the best choice.
-# Thus we've included 3 or 4 cross-platform choices:
-#
-# http://www.slant.co/topics/67/~what-are-the-best-programming-fonts
-# http://hivelogic.com/articles/top-10-programming-fonts
-#
-# 1.  Source Code Pro (OTF/TTF) — https://github.com/adobe-fonts/source-code-pro
-#     Open-source and created by Adobe, this is the premier monospace
-#     font. It is the preferred choice for the students (easiest to
-#     read at small sizes).
-# 2.  DejaVu Sans Mono (TTF) — http://dejavu-fonts.org/wiki/Main_Page
-#     Open-source and created for the Linux community, this font is
-#     very nice and compares well to Source Code Pro (SCP). Use on
-#     Linux if SCP renders poorly.
-# 3.  (Linux) Monaco (TTF) — https://github.com/cstrap/monaco-font
-#     Not clear on licensing. Monaco is very similar to Menlo, and is
-#     simple and clean - many students prefer it. Thus, if using
-#     Menlo instead of SCP on Mac, switch Mac to Monaco and Linux to
-#     Monaco in order to keep the look & feel similar.
-# 4.  Inconsolata (TTF) — https://www.google.com/fonts/specimen/Inconsolata
-#     Open-source and created to be similar to the MS font Consolas.
-#     A great programming font included in case students are used to
-#     programming with Consolas (in MS) or want another choice.
-#
-# The Installfest is currently using the versions:
-#
-# - Source Code Pro:  v2.010
-# - DejaVu Sans Mono: v2.35
-# - (Linux) Monaco:   ???
-# - Inconsolata:      v1.014
-
-MAC_FONTS="source-code-pro dejavu-sans-mono inconsolata"
-
-inform "Copying preferred programming fonts..." true
-
-for FONT_ZIP in $SCRIPT_FONTS; do
-  for MAC_FONT in $MAC_FONTS; do
-    if [[ $FONT_ZIP == *"$MAC_FONT"* ]]; then
-      FONT_DIR="${SCRIPT_FONTS%?}$MAC_FONT"
-
-      unzip -q "$FONT_ZIP" -d "$FONT_DIR"
-
-      OTF_FILE_LIST=$(find "$FONT_DIR" ! -type d | grep .otf$ | grep -v .woff | grep -v "._")
-      TTF_FILE_LIST=$(find "$FONT_DIR" ! -type d | grep .ttf$ | grep -v .woff | grep -v "._")
-
-      if [ -n "$OTF_FILE_LIST" ]; then
-        copy_files fonts_otf "${HOME}/Library/Fonts" "$OTF_FILE_LIST"
-      else
-        copy_files fonts_ttf "${HOME}/Library/Fonts" "$TTF_FILE_LIST"
-      fi
-
-      rm -rf "$FONT_DIR"
-    fi
-  done
-done
-
-show "Complete!"
-
-
+show "Setup is valid!"
 
 #-------------------------------------------------------------------------------
 # We're done! (utils/script_footer.sh)
@@ -414,5 +273,5 @@ show "Complete!"
 inform "We're done!" true
 echo "#-- fin -- #"
 
-warn "Please quit and re-open your terminal!" true
+fail "Please close your terminal and open a new one!" true
 
